# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/Ui_PyPlane.ui'
#
# Created: Wed Jun 24 11:46:39 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_pyplane(object):
    def setupUi(self, pyplane):
        pyplane.setObjectName(_fromUtf8("pyplane"))
        pyplane.resize(770, 757)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pyplane.sizePolicy().hasHeightForWidth())
        pyplane.setSizePolicy(sizePolicy)
        pyplane.setMinimumSize(QtCore.QSize(770, 757))
        self.centralwidget = QtGui.QWidget(pyplane)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.full = QtGui.QVBoxLayout()
        self.full.setObjectName(_fromUtf8("full"))
        self.inputBox = QtGui.QHBoxLayout()
        self.inputBox.setObjectName(_fromUtf8("inputBox"))
        self.syst = QtGui.QVBoxLayout()
        self.syst.setObjectName(_fromUtf8("syst"))
        self.title = QtGui.QLabel(self.centralwidget)
        self.title.setObjectName(_fromUtf8("title"))
        self.syst.addWidget(self.title)
        self.xDotBox = QtGui.QHBoxLayout()
        self.xDotBox.setObjectName(_fromUtf8("xDotBox"))
        self.xDotLabel = QtGui.QLabel(self.centralwidget)
        self.xDotLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xDotLabel.setObjectName(_fromUtf8("xDotLabel"))
        self.xDotBox.addWidget(self.xDotLabel)
        self.xDotLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.xDotLineEdit.setObjectName(_fromUtf8("xDotLineEdit"))
        self.xDotBox.addWidget(self.xDotLineEdit)
        self.submitButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submitButton.sizePolicy().hasHeightForWidth())
        self.submitButton.setSizePolicy(sizePolicy)
        self.submitButton.setMinimumSize(QtCore.QSize(0, 0))
        self.submitButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.submitButton.setObjectName(_fromUtf8("submitButton"))
        self.xDotBox.addWidget(self.submitButton)
        self.syst.addLayout(self.xDotBox)
        self.yDotBox = QtGui.QHBoxLayout()
        self.yDotBox.setObjectName(_fromUtf8("yDotBox"))
        self.yDotLabel = QtGui.QLabel(self.centralwidget)
        self.yDotLabel.setObjectName(_fromUtf8("yDotLabel"))
        self.yDotBox.addWidget(self.yDotLabel)
        self.yDotLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.yDotLineEdit.setObjectName(_fromUtf8("yDotLineEdit"))
        self.yDotBox.addWidget(self.yDotLineEdit)
        self.clearButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setMinimumSize(QtCore.QSize(0, 0))
        self.clearButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.yDotBox.addWidget(self.clearButton)
        self.syst.addLayout(self.yDotBox)
        self.inputBox.addLayout(self.syst)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.inputBox.addWidget(self.line)
        self.funcBox = QtGui.QVBoxLayout()
        self.funcBox.setObjectName(_fromUtf8("funcBox"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.funcBox.addWidget(self.label)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.yLabel = QtGui.QLabel(self.centralwidget)
        self.yLabel.setObjectName(_fromUtf8("yLabel"))
        self.horizontalLayout_6.addWidget(self.yLabel)
        self.yLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.yLineEdit.setObjectName(_fromUtf8("yLineEdit"))
        self.horizontalLayout_6.addWidget(self.yLineEdit)
        self.FctPlotButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FctPlotButton.sizePolicy().hasHeightForWidth())
        self.FctPlotButton.setSizePolicy(sizePolicy)
        self.FctPlotButton.setMinimumSize(QtCore.QSize(0, 0))
        self.FctPlotButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.FctPlotButton.setObjectName(_fromUtf8("FctPlotButton"))
        self.horizontalLayout_6.addWidget(self.FctPlotButton)
        self.funcBox.addLayout(self.horizontalLayout_6)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.FctClearButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FctClearButton.sizePolicy().hasHeightForWidth())
        self.FctClearButton.setSizePolicy(sizePolicy)
        self.FctClearButton.setMinimumSize(QtCore.QSize(0, 0))
        self.FctClearButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.FctClearButton.setObjectName(_fromUtf8("FctClearButton"))
        self.horizontalLayout_8.addWidget(self.FctClearButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.funcBox.addLayout(self.verticalLayout_10)
        self.inputBox.addLayout(self.funcBox)
        self.full.addLayout(self.inputBox)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.phaseplane = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phaseplane.sizePolicy().hasHeightForWidth())
        self.phaseplane.setSizePolicy(sizePolicy)
        self.phaseplane.setObjectName(_fromUtf8("phaseplane"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.phaseplane)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.widget = QtGui.QWidget(self.phaseplane)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(110, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.PP_WindowRangeLabel = QtGui.QLabel(self.widget)
        self.PP_WindowRangeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_WindowRangeLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PP_WindowRangeLabel.setObjectName(_fromUtf8("PP_WindowRangeLabel"))
        self.verticalLayout.addWidget(self.PP_WindowRangeLabel)
        self.PP_xminLabel = QtGui.QLabel(self.widget)
        self.PP_xminLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.PP_xminLabel.setFont(font)
        self.PP_xminLabel.setObjectName(_fromUtf8("PP_xminLabel"))
        self.verticalLayout.addWidget(self.PP_xminLabel)
        self.PP_xminLineEdit = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PP_xminLineEdit.sizePolicy().hasHeightForWidth())
        self.PP_xminLineEdit.setSizePolicy(sizePolicy)
        self.PP_xminLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_xminLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PP_xminLineEdit.setObjectName(_fromUtf8("PP_xminLineEdit"))
        self.verticalLayout.addWidget(self.PP_xminLineEdit)
        self.PP_xmaxLabel = QtGui.QLabel(self.widget)
        self.PP_xmaxLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_xmaxLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.PP_xmaxLabel.setFont(font)
        self.PP_xmaxLabel.setObjectName(_fromUtf8("PP_xmaxLabel"))
        self.verticalLayout.addWidget(self.PP_xmaxLabel)
        self.PP_xmaxLineEdit = QtGui.QLineEdit(self.widget)
        self.PP_xmaxLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_xmaxLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PP_xmaxLineEdit.setObjectName(_fromUtf8("PP_xmaxLineEdit"))
        self.verticalLayout.addWidget(self.PP_xmaxLineEdit)
        self.PP_yminLabel = QtGui.QLabel(self.widget)
        self.PP_yminLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_yminLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.PP_yminLabel.setFont(font)
        self.PP_yminLabel.setObjectName(_fromUtf8("PP_yminLabel"))
        self.verticalLayout.addWidget(self.PP_yminLabel)
        self.PP_yminLineEdit = QtGui.QLineEdit(self.widget)
        self.PP_yminLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_yminLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PP_yminLineEdit.setObjectName(_fromUtf8("PP_yminLineEdit"))
        self.verticalLayout.addWidget(self.PP_yminLineEdit)
        self.PP_ymaxLabel = QtGui.QLabel(self.widget)
        self.PP_ymaxLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_ymaxLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.PP_ymaxLabel.setFont(font)
        self.PP_ymaxLabel.setObjectName(_fromUtf8("PP_ymaxLabel"))
        self.verticalLayout.addWidget(self.PP_ymaxLabel)
        self.PP_ymaxLineEdit = QtGui.QLineEdit(self.widget)
        self.PP_ymaxLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_ymaxLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PP_ymaxLineEdit.setObjectName(_fromUtf8("PP_ymaxLineEdit"))
        self.verticalLayout.addWidget(self.PP_ymaxLineEdit)
        self.PP_SetButton = QtGui.QPushButton(self.widget)
        self.PP_SetButton.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_SetButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PP_SetButton.setObjectName(_fromUtf8("PP_SetButton"))
        self.verticalLayout.addWidget(self.PP_SetButton)
        self.PP_ZoomButton = QtGui.QPushButton(self.widget)
        self.PP_ZoomButton.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_ZoomButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PP_ZoomButton.setObjectName(_fromUtf8("PP_ZoomButton"))
        self.verticalLayout.addWidget(self.PP_ZoomButton)
        self.PP_RefreshButton = QtGui.QPushButton(self.widget)
        self.PP_RefreshButton.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_RefreshButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PP_RefreshButton.setObjectName(_fromUtf8("PP_RefreshButton"))
        self.verticalLayout.addWidget(self.PP_RefreshButton)
        spacerItem1 = QtGui.QSpacerItem(10, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.IntegrationLabel = QtGui.QLabel(self.widget)
        self.IntegrationLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.IntegrationLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.IntegrationLabel.setObjectName(_fromUtf8("IntegrationLabel"))
        self.verticalLayout.addWidget(self.IntegrationLabel)
        self.forwardCheckbox = QtGui.QCheckBox(self.widget)
        self.forwardCheckbox.setMinimumSize(QtCore.QSize(100, 0))
        self.forwardCheckbox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.forwardCheckbox.setFont(font)
        self.forwardCheckbox.setObjectName(_fromUtf8("forwardCheckbox"))
        self.verticalLayout.addWidget(self.forwardCheckbox)
        self.backwardCheckbox = QtGui.QCheckBox(self.widget)
        self.backwardCheckbox.setMinimumSize(QtCore.QSize(100, 0))
        self.backwardCheckbox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.backwardCheckbox.setFont(font)
        self.backwardCheckbox.setObjectName(_fromUtf8("backwardCheckbox"))
        self.verticalLayout.addWidget(self.backwardCheckbox)
        spacerItem2 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.PP_InitialConditionLabel = QtGui.QLabel(self.widget)
        self.PP_InitialConditionLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_InitialConditionLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PP_InitialConditionLabel.setObjectName(_fromUtf8("PP_InitialConditionLabel"))
        self.verticalLayout.addWidget(self.PP_InitialConditionLabel)
        self.PP_x_initLabel = QtGui.QLabel(self.widget)
        self.PP_x_initLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_x_initLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.PP_x_initLabel.setFont(font)
        self.PP_x_initLabel.setObjectName(_fromUtf8("PP_x_initLabel"))
        self.verticalLayout.addWidget(self.PP_x_initLabel)
        self.PP_x_initLineEdit = QtGui.QLineEdit(self.widget)
        self.PP_x_initLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_x_initLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PP_x_initLineEdit.setObjectName(_fromUtf8("PP_x_initLineEdit"))
        self.verticalLayout.addWidget(self.PP_x_initLineEdit)
        self.PP_y_initLabel = QtGui.QLabel(self.widget)
        self.PP_y_initLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_y_initLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.PP_y_initLabel.setFont(font)
        self.PP_y_initLabel.setObjectName(_fromUtf8("PP_y_initLabel"))
        self.verticalLayout.addWidget(self.PP_y_initLabel)
        self.PP_y_initLineEdit = QtGui.QLineEdit(self.widget)
        self.PP_y_initLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_y_initLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PP_y_initLineEdit.setObjectName(_fromUtf8("PP_y_initLineEdit"))
        self.verticalLayout.addWidget(self.PP_y_initLineEdit)
        self.PP_CreateTrajectoryButton = QtGui.QPushButton(self.widget)
        self.PP_CreateTrajectoryButton.setMinimumSize(QtCore.QSize(100, 0))
        self.PP_CreateTrajectoryButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PP_CreateTrajectoryButton.setObjectName(_fromUtf8("PP_CreateTrajectoryButton"))
        self.verticalLayout.addWidget(self.PP_CreateTrajectoryButton)
        self.horizontalLayout_2.addWidget(self.widget)
        self.frame1 = QtGui.QFrame(self.phaseplane)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1.sizePolicy().hasHeightForWidth())
        self.frame1.setSizePolicy(sizePolicy)
        self.frame1.setMinimumSize(QtCore.QSize(0, 0))
        self.frame1.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame1.setFrameShadow(QtGui.QFrame.Plain)
        self.frame1.setLineWidth(0)
        self.frame1.setObjectName(_fromUtf8("frame1"))
        self.horizontalLayout_2.addWidget(self.frame1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.phaseplane, _fromUtf8(""))
        self.x_t = QtGui.QWidget()
        self.x_t.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_t.sizePolicy().hasHeightForWidth())
        self.x_t.setSizePolicy(sizePolicy)
        self.x_t.setObjectName(_fromUtf8("x_t"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.x_t)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.framsd = QtGui.QWidget(self.x_t)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framsd.sizePolicy().hasHeightForWidth())
        self.framsd.setSizePolicy(sizePolicy)
        self.framsd.setMinimumSize(QtCore.QSize(110, 0))
        self.framsd.setObjectName(_fromUtf8("framsd"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.framsd)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.X_WindowRangeLabel = QtGui.QLabel(self.framsd)
        self.X_WindowRangeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.X_WindowRangeLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.X_WindowRangeLabel.setObjectName(_fromUtf8("X_WindowRangeLabel"))
        self.verticalLayout_6.addWidget(self.X_WindowRangeLabel)
        self.X_tminLabel = QtGui.QLabel(self.framsd)
        self.X_tminLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.X_tminLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.X_tminLabel.setFont(font)
        self.X_tminLabel.setObjectName(_fromUtf8("X_tminLabel"))
        self.verticalLayout_6.addWidget(self.X_tminLabel)
        self.X_tminLineEdit = QtGui.QLineEdit(self.framsd)
        self.X_tminLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.X_tminLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.X_tminLineEdit.setObjectName(_fromUtf8("X_tminLineEdit"))
        self.verticalLayout_6.addWidget(self.X_tminLineEdit)
        self.X_tmaxLabel = QtGui.QLabel(self.framsd)
        self.X_tmaxLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.X_tmaxLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.X_tmaxLabel.setFont(font)
        self.X_tmaxLabel.setObjectName(_fromUtf8("X_tmaxLabel"))
        self.verticalLayout_6.addWidget(self.X_tmaxLabel)
        self.X_tmaxLineEdit = QtGui.QLineEdit(self.framsd)
        self.X_tmaxLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.X_tmaxLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.X_tmaxLineEdit.setObjectName(_fromUtf8("X_tmaxLineEdit"))
        self.verticalLayout_6.addWidget(self.X_tmaxLineEdit)
        self.X_xminLabel = QtGui.QLabel(self.framsd)
        self.X_xminLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.X_xminLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.X_xminLabel.setFont(font)
        self.X_xminLabel.setObjectName(_fromUtf8("X_xminLabel"))
        self.verticalLayout_6.addWidget(self.X_xminLabel)
        self.X_xminLineEdit = QtGui.QLineEdit(self.framsd)
        self.X_xminLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.X_xminLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.X_xminLineEdit.setObjectName(_fromUtf8("X_xminLineEdit"))
        self.verticalLayout_6.addWidget(self.X_xminLineEdit)
        self.X_xmax_label = QtGui.QLabel(self.framsd)
        self.X_xmax_label.setMinimumSize(QtCore.QSize(100, 0))
        self.X_xmax_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.X_xmax_label.setFont(font)
        self.X_xmax_label.setObjectName(_fromUtf8("X_xmax_label"))
        self.verticalLayout_6.addWidget(self.X_xmax_label)
        self.X_xmaxLineEdit = QtGui.QLineEdit(self.framsd)
        self.X_xmaxLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.X_xmaxLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.X_xmaxLineEdit.setObjectName(_fromUtf8("X_xmaxLineEdit"))
        self.verticalLayout_6.addWidget(self.X_xmaxLineEdit)
        self.X_SetButton = QtGui.QPushButton(self.framsd)
        self.X_SetButton.setMinimumSize(QtCore.QSize(100, 0))
        self.X_SetButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.X_SetButton.setObjectName(_fromUtf8("X_SetButton"))
        self.verticalLayout_6.addWidget(self.X_SetButton)
        self.X_ZoomButton = QtGui.QPushButton(self.framsd)
        self.X_ZoomButton.setMinimumSize(QtCore.QSize(100, 0))
        self.X_ZoomButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.X_ZoomButton.setObjectName(_fromUtf8("X_ZoomButton"))
        self.verticalLayout_6.addWidget(self.X_ZoomButton)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_3.addWidget(self.framsd)
        self.frame2 = QtGui.QFrame(self.x_t)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame2.sizePolicy().hasHeightForWidth())
        self.frame2.setSizePolicy(sizePolicy)
        self.frame2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame2.setLineWidth(0)
        self.frame2.setObjectName(_fromUtf8("frame2"))
        self.horizontalLayout_3.addWidget(self.frame2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.x_t, _fromUtf8(""))
        self.y_t = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_t.sizePolicy().hasHeightForWidth())
        self.y_t.setSizePolicy(sizePolicy)
        self.y_t.setObjectName(_fromUtf8("y_t"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.y_t)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.widget1 = QtGui.QWidget(self.y_t)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setMinimumSize(QtCore.QSize(110, 0))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.Y_WindowRangeLabel = QtGui.QLabel(self.widget1)
        self.Y_WindowRangeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.Y_WindowRangeLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Y_WindowRangeLabel.setObjectName(_fromUtf8("Y_WindowRangeLabel"))
        self.verticalLayout_8.addWidget(self.Y_WindowRangeLabel)
        self.Y_tminLabel = QtGui.QLabel(self.widget1)
        self.Y_tminLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.Y_tminLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.Y_tminLabel.setFont(font)
        self.Y_tminLabel.setObjectName(_fromUtf8("Y_tminLabel"))
        self.verticalLayout_8.addWidget(self.Y_tminLabel)
        self.Y_tminLineEdit = QtGui.QLineEdit(self.widget1)
        self.Y_tminLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.Y_tminLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Y_tminLineEdit.setObjectName(_fromUtf8("Y_tminLineEdit"))
        self.verticalLayout_8.addWidget(self.Y_tminLineEdit)
        self.Y_tmaxLabel = QtGui.QLabel(self.widget1)
        self.Y_tmaxLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.Y_tmaxLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.Y_tmaxLabel.setFont(font)
        self.Y_tmaxLabel.setObjectName(_fromUtf8("Y_tmaxLabel"))
        self.verticalLayout_8.addWidget(self.Y_tmaxLabel)
        self.Y_tmaxLineEdit = QtGui.QLineEdit(self.widget1)
        self.Y_tmaxLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.Y_tmaxLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Y_tmaxLineEdit.setObjectName(_fromUtf8("Y_tmaxLineEdit"))
        self.verticalLayout_8.addWidget(self.Y_tmaxLineEdit)
        self.Y_yminLabel = QtGui.QLabel(self.widget1)
        self.Y_yminLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.Y_yminLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.Y_yminLabel.setFont(font)
        self.Y_yminLabel.setObjectName(_fromUtf8("Y_yminLabel"))
        self.verticalLayout_8.addWidget(self.Y_yminLabel)
        self.Y_yminLineEdit = QtGui.QLineEdit(self.widget1)
        self.Y_yminLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.Y_yminLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Y_yminLineEdit.setObjectName(_fromUtf8("Y_yminLineEdit"))
        self.verticalLayout_8.addWidget(self.Y_yminLineEdit)
        self.Y_ymaxLabel = QtGui.QLabel(self.widget1)
        self.Y_ymaxLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.Y_ymaxLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.Y_ymaxLabel.setFont(font)
        self.Y_ymaxLabel.setObjectName(_fromUtf8("Y_ymaxLabel"))
        self.verticalLayout_8.addWidget(self.Y_ymaxLabel)
        self.Y_ymaxLineEdit = QtGui.QLineEdit(self.widget1)
        self.Y_ymaxLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.Y_ymaxLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Y_ymaxLineEdit.setObjectName(_fromUtf8("Y_ymaxLineEdit"))
        self.verticalLayout_8.addWidget(self.Y_ymaxLineEdit)
        self.Y_SetButton = QtGui.QPushButton(self.widget1)
        self.Y_SetButton.setMinimumSize(QtCore.QSize(100, 0))
        self.Y_SetButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Y_SetButton.setObjectName(_fromUtf8("Y_SetButton"))
        self.verticalLayout_8.addWidget(self.Y_SetButton)
        self.Y_ZoomButton = QtGui.QPushButton(self.widget1)
        self.Y_ZoomButton.setMinimumSize(QtCore.QSize(100, 0))
        self.Y_ZoomButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Y_ZoomButton.setObjectName(_fromUtf8("Y_ZoomButton"))
        self.verticalLayout_8.addWidget(self.Y_ZoomButton)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.horizontalLayout_5.addWidget(self.widget1)
        self.frame3 = QtGui.QFrame(self.y_t)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame3.sizePolicy().hasHeightForWidth())
        self.frame3.setSizePolicy(sizePolicy)
        self.frame3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame3.setLineWidth(0)
        self.frame3.setObjectName(_fromUtf8("frame3"))
        self.horizontalLayout_5.addWidget(self.frame3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.y_t, _fromUtf8(""))
        self.settings = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings.sizePolicy().hasHeightForWidth())
        self.settings.setSizePolicy(sizePolicy)
        self.settings.setObjectName(_fromUtf8("settings"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.settings)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.widget_2 = QtGui.QWidget(self.settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(110, 0))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_9.setSpacing(1)
        self.verticalLayout_9.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_9.addItem(spacerItem5)
        self.SectionListView = QtGui.QListView(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SectionListView.sizePolicy().hasHeightForWidth())
        self.SectionListView.setSizePolicy(sizePolicy)
        self.SectionListView.setMinimumSize(QtCore.QSize(100, 0))
        self.SectionListView.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SectionListView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.SectionListView.setObjectName(_fromUtf8("SectionListView"))
        self.verticalLayout_9.addWidget(self.SectionListView)
        self.horizontalLayout_7.addWidget(self.widget_2)
        self.SectionLayout = QtGui.QFormLayout()
        self.SectionLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.SectionLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SectionLayout.setHorizontalSpacing(0)
        self.SectionLayout.setVerticalSpacing(5)
        self.SectionLayout.setObjectName(_fromUtf8("SectionLayout"))
        self.SetupSectionTitle = QtGui.QLabel(self.settings)
        self.SetupSectionTitle.setMinimumSize(QtCore.QSize(200, 30))
        self.SetupSectionTitle.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SetupSectionTitle.setFont(font)
        self.SetupSectionTitle.setText(_fromUtf8(""))
        self.SetupSectionTitle.setObjectName(_fromUtf8("SetupSectionTitle"))
        self.SectionLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.SetupSectionTitle)
        self.horizontalLayout_7.addLayout(self.SectionLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.SetupApplyButton = QtGui.QPushButton(self.settings)
        self.SetupApplyButton.setMinimumSize(QtCore.QSize(100, 0))
        self.SetupApplyButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SetupApplyButton.setObjectName(_fromUtf8("SetupApplyButton"))
        self.horizontalLayout.addWidget(self.SetupApplyButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.settings, _fromUtf8(""))
        self.full.addWidget(self.tabWidget)
        self.logField = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logField.sizePolicy().hasHeightForWidth())
        self.logField.setSizePolicy(sizePolicy)
        self.logField.setMinimumSize(QtCore.QSize(0, 0))
        self.logField.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.logField.setFont(font)
        self.logField.setMouseTracking(False)
        self.logField.setAutoFillBackground(True)
        self.logField.setStyleSheet(_fromUtf8("QTextEdit { background-color: rgb(0, 0, 0) }"))
        self.logField.setFrameShape(QtGui.QFrame.NoFrame)
        self.logField.setFrameShadow(QtGui.QFrame.Plain)
        self.logField.setLineWidth(0)
        self.logField.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.logField.setObjectName(_fromUtf8("logField"))
        self.full.addWidget(self.logField)
        self.gridLayout.addLayout(self.full, 0, 0, 1, 1)
        pyplane.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(pyplane)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        pyplane.setMenuBar(self.menubar)
        self.actionNew = QtGui.QAction(pyplane)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(pyplane)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(pyplane)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionQuit = QtGui.QAction(pyplane)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionNullclines = QtGui.QAction(pyplane)
        self.actionNullclines.setObjectName(_fromUtf8("actionNullclines"))
        self.action = QtGui.QAction(pyplane)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_2 = QtGui.QAction(pyplane)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.actionPyPlane_Help = QtGui.QAction(pyplane)
        self.actionPyPlane_Help.setObjectName(_fromUtf8("actionPyPlane_Help"))
        self.actionAbout = QtGui.QAction(pyplane)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))

        self.retranslateUi(pyplane)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("activated()")), pyplane.close)
        QtCore.QMetaObject.connectSlotsByName(pyplane)
        pyplane.setTabOrder(self.tabWidget, self.PP_xminLineEdit)
        pyplane.setTabOrder(self.PP_xminLineEdit, self.PP_xmaxLineEdit)
        pyplane.setTabOrder(self.PP_xmaxLineEdit, self.PP_yminLineEdit)
        pyplane.setTabOrder(self.PP_yminLineEdit, self.PP_ymaxLineEdit)
        pyplane.setTabOrder(self.PP_ymaxLineEdit, self.PP_SetButton)
        pyplane.setTabOrder(self.PP_SetButton, self.PP_ZoomButton)
        pyplane.setTabOrder(self.PP_ZoomButton, self.forwardCheckbox)
        pyplane.setTabOrder(self.forwardCheckbox, self.backwardCheckbox)
        pyplane.setTabOrder(self.backwardCheckbox, self.PP_x_initLineEdit)
        pyplane.setTabOrder(self.PP_x_initLineEdit, self.PP_y_initLineEdit)
        pyplane.setTabOrder(self.PP_y_initLineEdit, self.PP_CreateTrajectoryButton)
        pyplane.setTabOrder(self.PP_CreateTrajectoryButton, self.X_tminLineEdit)
        pyplane.setTabOrder(self.X_tminLineEdit, self.X_tmaxLineEdit)
        pyplane.setTabOrder(self.X_tmaxLineEdit, self.X_xminLineEdit)
        pyplane.setTabOrder(self.X_xminLineEdit, self.X_xmaxLineEdit)
        pyplane.setTabOrder(self.X_xmaxLineEdit, self.X_SetButton)
        pyplane.setTabOrder(self.X_SetButton, self.X_ZoomButton)
        pyplane.setTabOrder(self.X_ZoomButton, self.Y_tminLineEdit)
        pyplane.setTabOrder(self.Y_tminLineEdit, self.Y_tmaxLineEdit)
        pyplane.setTabOrder(self.Y_tmaxLineEdit, self.Y_yminLineEdit)
        pyplane.setTabOrder(self.Y_yminLineEdit, self.Y_ymaxLineEdit)
        pyplane.setTabOrder(self.Y_ymaxLineEdit, self.Y_SetButton)
        pyplane.setTabOrder(self.Y_SetButton, self.Y_ZoomButton)
        pyplane.setTabOrder(self.Y_ZoomButton, self.logField)

    def retranslateUi(self, pyplane):
        pyplane.setWindowTitle(_translate("pyplane", "MainWindow", None))
        self.title.setText(_translate("pyplane", "Dynamical System", None))
        self.xDotLabel.setText(_translate("pyplane", "x\' = ", None))
        self.xDotLineEdit.setPlaceholderText(_translate("pyplane", "y", None))
        self.submitButton.setText(_translate("pyplane", "Submit System", None))
        self.yDotLabel.setText(_translate("pyplane", "y\' = ", None))
        self.yDotLineEdit.setPlaceholderText(_translate("pyplane", "x-x**3", None))
        self.clearButton.setText(_translate("pyplane", "Clear Trajectories", None))
        self.label.setText(_translate("pyplane", "Additional Function:", None))
        self.yLabel.setText(_translate("pyplane", "0 = f(x,y) =", None))
        self.yLineEdit.setPlaceholderText(_translate("pyplane", "x**2+y**2-4", None))
        self.FctPlotButton.setText(_translate("pyplane", "Plot", None))
        self.FctClearButton.setText(_translate("pyplane", "Clear Plots", None))
        self.PP_WindowRangeLabel.setText(_translate("pyplane", "Window Range", None))
        self.PP_xminLabel.setText(_translate("pyplane", "xmin", None))
        self.PP_xmaxLabel.setText(_translate("pyplane", "xmax", None))
        self.PP_yminLabel.setText(_translate("pyplane", "ymin", None))
        self.PP_ymaxLabel.setText(_translate("pyplane", "ymax", None))
        self.PP_SetButton.setText(_translate("pyplane", "Set", None))
        self.PP_ZoomButton.setText(_translate("pyplane", "Zoom", None))
        self.PP_RefreshButton.setText(_translate("pyplane", "Refresh", None))
        self.IntegrationLabel.setText(_translate("pyplane", "Integration", None))
        self.forwardCheckbox.setText(_translate("pyplane", "Forward", None))
        self.backwardCheckbox.setText(_translate("pyplane", "Backward", None))
        self.PP_InitialConditionLabel.setText(_translate("pyplane", "Initial Condition", None))
        self.PP_x_initLabel.setText(_translate("pyplane", "x-Coordinate", None))
        self.PP_y_initLabel.setText(_translate("pyplane", "y-Coordinate", None))
        self.PP_CreateTrajectoryButton.setText(_translate("pyplane", "Create", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.phaseplane), _translate("pyplane", "Phase Plane", None))
        self.X_WindowRangeLabel.setText(_translate("pyplane", "Window Range", None))
        self.X_tminLabel.setText(_translate("pyplane", "tmin", None))
        self.X_tmaxLabel.setText(_translate("pyplane", "tmax", None))
        self.X_xminLabel.setText(_translate("pyplane", "xmin", None))
        self.X_xmax_label.setText(_translate("pyplane", "xmax", None))
        self.X_SetButton.setText(_translate("pyplane", "Set", None))
        self.X_ZoomButton.setText(_translate("pyplane", "Zoom", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.x_t), _translate("pyplane", "x(t)", None))
        self.Y_WindowRangeLabel.setText(_translate("pyplane", "Window Range", None))
        self.Y_tminLabel.setText(_translate("pyplane", "tmin", None))
        self.Y_tmaxLabel.setText(_translate("pyplane", "tmax", None))
        self.Y_yminLabel.setText(_translate("pyplane", "ymin", None))
        self.Y_ymaxLabel.setText(_translate("pyplane", "ymax", None))
        self.Y_SetButton.setText(_translate("pyplane", "Set", None))
        self.Y_ZoomButton.setText(_translate("pyplane", "Zoom", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.y_t), _translate("pyplane", "y(t)", None))
        self.SetupApplyButton.setText(_translate("pyplane", "Apply", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("pyplane", "Settings", None))
        self.actionNew.setText(_translate("pyplane", "New", None))
        self.actionOpen.setText(_translate("pyplane", "Open", None))
        self.actionSave.setText(_translate("pyplane", "Save", None))
        self.actionQuit.setText(_translate("pyplane", "Quit", None))
        self.actionNullclines.setText(_translate("pyplane", "Nullclines", None))
        self.action.setText(_translate("pyplane", "Vector Field", None))
        self.action_2.setText(_translate("pyplane", "...", None))
        self.actionPyPlane_Help.setText(_translate("pyplane", "PyPlane Help", None))
        self.actionAbout.setText(_translate("pyplane", "About", None))

