# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/Ui_ThreeDWidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ThreeDWidget(object):
    def setupUi(self, ThreeDWidget):
        ThreeDWidget.setObjectName(_fromUtf8("ThreeDWidget"))
        ThreeDWidget.resize(662, 593)
        self.horizontalLayout = QtGui.QHBoxLayout(ThreeDWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_9 = QtGui.QLabel(ThreeDWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.param_minLabel = QtGui.QLabel(ThreeDWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.param_minLabel.setFont(font)
        self.param_minLabel.setObjectName(_fromUtf8("param_minLabel"))
        self.verticalLayout.addWidget(self.param_minLabel)
        self.tminLineEdit = QtGui.QLineEdit(ThreeDWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tminLineEdit.sizePolicy().hasHeightForWidth())
        self.tminLineEdit.setSizePolicy(sizePolicy)
        self.tminLineEdit.setMinimumSize(QtCore.QSize(100, 22))
        self.tminLineEdit.setObjectName(_fromUtf8("tminLineEdit"))
        self.verticalLayout.addWidget(self.tminLineEdit)
        self.param_maxLabel = QtGui.QLabel(ThreeDWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.param_maxLabel.setFont(font)
        self.param_maxLabel.setObjectName(_fromUtf8("param_maxLabel"))
        self.verticalLayout.addWidget(self.param_maxLabel)
        self.tmaxLineEdit = QtGui.QLineEdit(ThreeDWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tmaxLineEdit.sizePolicy().hasHeightForWidth())
        self.tmaxLineEdit.setSizePolicy(sizePolicy)
        self.tmaxLineEdit.setMinimumSize(QtCore.QSize(0, 22))
        self.tmaxLineEdit.setObjectName(_fromUtf8("tmaxLineEdit"))
        self.verticalLayout.addWidget(self.tmaxLineEdit)
        self.label_3 = QtGui.QLabel(ThreeDWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.xminLineEdit = QtGui.QLineEdit(ThreeDWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xminLineEdit.sizePolicy().hasHeightForWidth())
        self.xminLineEdit.setSizePolicy(sizePolicy)
        self.xminLineEdit.setMinimumSize(QtCore.QSize(0, 22))
        self.xminLineEdit.setObjectName(_fromUtf8("xminLineEdit"))
        self.verticalLayout.addWidget(self.xminLineEdit)
        self.label_4 = QtGui.QLabel(ThreeDWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.xmaxLineEdit = QtGui.QLineEdit(ThreeDWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xmaxLineEdit.sizePolicy().hasHeightForWidth())
        self.xmaxLineEdit.setSizePolicy(sizePolicy)
        self.xmaxLineEdit.setMinimumSize(QtCore.QSize(100, 22))
        self.xmaxLineEdit.setObjectName(_fromUtf8("xmaxLineEdit"))
        self.verticalLayout.addWidget(self.xmaxLineEdit)
        self.label = QtGui.QLabel(ThreeDWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.yminLineEdit = QtGui.QLineEdit(ThreeDWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yminLineEdit.sizePolicy().hasHeightForWidth())
        self.yminLineEdit.setSizePolicy(sizePolicy)
        self.yminLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.yminLineEdit.setObjectName(_fromUtf8("yminLineEdit"))
        self.verticalLayout.addWidget(self.yminLineEdit)
        self.label_2 = QtGui.QLabel(ThreeDWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.ymaxLineEdit = QtGui.QLineEdit(ThreeDWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ymaxLineEdit.sizePolicy().hasHeightForWidth())
        self.ymaxLineEdit.setSizePolicy(sizePolicy)
        self.ymaxLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.ymaxLineEdit.setObjectName(_fromUtf8("ymaxLineEdit"))
        self.verticalLayout.addWidget(self.ymaxLineEdit)
        self.SetButton = QtGui.QPushButton(ThreeDWidget)
        self.SetButton.setObjectName(_fromUtf8("SetButton"))
        self.verticalLayout.addWidget(self.SetButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.mpl_layout = QtGui.QVBoxLayout()
        self.mpl_layout.setObjectName(_fromUtf8("mpl_layout"))
        self.frame = QtGui.QWidget(ThreeDWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(444, 0))
        self.frame.setObjectName(_fromUtf8("frame"))
        self.mpl_layout.addWidget(self.frame)
        self.horizontalLayout.addLayout(self.mpl_layout)

        self.retranslateUi(ThreeDWidget)
        QtCore.QMetaObject.connectSlotsByName(ThreeDWidget)

    def retranslateUi(self, ThreeDWidget):
        ThreeDWidget.setWindowTitle(_translate("ThreeDWidget", "Form", None))
        self.label_9.setText(_translate("ThreeDWidget", "Window Range", None))
        self.param_minLabel.setText(_translate("ThreeDWidget", "tmin", None))
        self.param_maxLabel.setText(_translate("ThreeDWidget", "tmax", None))
        self.label_3.setText(_translate("ThreeDWidget", "xmin", None))
        self.label_4.setText(_translate("ThreeDWidget", "xmax", None))
        self.label.setText(_translate("ThreeDWidget", "ymin", None))
        self.label_2.setText(_translate("ThreeDWidget", "ymax", None))
        self.SetButton.setText(_translate("ThreeDWidget", "Set", None))

